apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-kxxxhekz
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-kxxxhekz:b321a4efe6f9677b13b8190db1a46fac4e2b5b96@sha256:c84dd813764ef2348ac230aeaf9483fbffc3a768e43deddeb8d62184b226e46f
        name: container-image  
